-- ============================================================
--  listahub_db.sql  –  Complete Database Schema
--  Based on ERD diagram (May 2026)
--
--  Requirements covered:
--   ✅ Prepared Statements (enforced in PHP)
--   ✅ SQL Triggers (5 triggers)
--   ✅ Stored Procedures (4 procedures)
--   ✅ Transactions (BEGIN / COMMIT / ROLLBACK)
--   ✅ SQL View (5 views, Manager Dashboard joins 4+ tables)
--   ✅ Indexes (on frequently searched columns)
--   ✅ COUNT(), SUM(), JOIN used in views & queries
-- ============================================================

-- Drop and recreate database cleanly
DROP DATABASE IF EXISTS listahub_db;

CREATE DATABASE listahub_db
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE listahub_db;

-- ============================================================
--  TABLES  (in FK-dependency order)
-- ============================================================

-- -----------------------------------------------------------
--  1. User  (store owner — store_name lives here per ERD)
-- -----------------------------------------------------------
CREATE TABLE User (
    user_id       INT UNSIGNED    AUTO_INCREMENT PRIMARY KEY,
    username      VARCHAR(50)     NOT NULL UNIQUE,
    email         VARCHAR(100)    NOT NULL UNIQUE,
    password_hash VARCHAR(255)    NOT NULL,
    store_name    VARCHAR(100)    NOT NULL,
    created_at    DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login    DATETIME        NULL
) ENGINE=InnoDB;

-- -----------------------------------------------------------
--  2. Category
-- -----------------------------------------------------------
CREATE TABLE Category (
    category_id   TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    category_name VARCHAR(50)      NOT NULL UNIQUE
) ENGINE=InnoDB;

-- -----------------------------------------------------------
--  3. Product  (FK → User, Category)
--     SKU is auto-generated by trigger after INSERT
--     status is auto-maintained by BEFORE UPDATE trigger
-- -----------------------------------------------------------
CREATE TABLE Product (
    product_id          INT UNSIGNED    AUTO_INCREMENT PRIMARY KEY,
    image_url           VARCHAR(255)    NULL,
    product_name        VARCHAR(100)    NOT NULL,
    sku                 VARCHAR(50)     NOT NULL DEFAULT 'PENDING',
    category_id         TINYINT UNSIGNED NOT NULL,
    cost_price          DECIMAL(10,2)   NOT NULL DEFAULT 0.00 CHECK (cost_price >= 0),
    retail_price        DECIMAL(10,2)   NOT NULL DEFAULT 0.00 CHECK (retail_price >= 0),
    quantity            INT             NOT NULL DEFAULT 0    CHECK (quantity >= 0),
    low_stock_threshold TINYINT UNSIGNED NOT NULL DEFAULT 9,
    status              ENUM('In Stock','Low Stock','Out of Stock') NOT NULL DEFAULT 'Out of Stock',
    expiration_date     DATE            NULL,
    created_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_id             INT UNSIGNED    NOT NULL,

    CONSTRAINT fk_product_category FOREIGN KEY (category_id)
        REFERENCES Category(category_id) ON UPDATE CASCADE,
    CONSTRAINT fk_product_user FOREIGN KEY (user_id)
        REFERENCES User(user_id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

-- -----------------------------------------------------------
--  4. Inventory_Log  (FK → Product)
-- -----------------------------------------------------------
CREATE TABLE Inventory_Log (
    log_id            INT UNSIGNED    AUTO_INCREMENT PRIMARY KEY,
    product_id        INT UNSIGNED    NOT NULL,
    movement_type     ENUM('in','out') NOT NULL,
    quantity_change   INT             NOT NULL CHECK (quantity_change > 0),
    stock_before      INT             NOT NULL,
    stock_after       INT             NOT NULL,
    reference_type    ENUM('restock','sale','manual') NOT NULL,
    reference_id      INT UNSIGNED    NULL,
    adjustment_reason ENUM(
                          'Damaged Goods',
                          'Expired Items',
                          'Stock Count Correction',
                          'Theft/Loss',
                          'Returned to Supplier',
                          'Other'
                      ) NULL,
    log_date          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_invlog_product FOREIGN KEY (product_id)
        REFERENCES Product(product_id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

-- -----------------------------------------------------------
--  5. Restock_Transaction
-- -----------------------------------------------------------
CREATE TABLE Restock_Transaction (
    restock_id   INT UNSIGNED   AUTO_INCREMENT PRIMARY KEY,
    restock_date DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_cost   DECIMAL(12,2)  NOT NULL DEFAULT 0.00 CHECK (total_cost >= 0)
) ENGINE=InnoDB;

-- -----------------------------------------------------------
--  6. Restock_Item  (FK → Restock_Transaction, Product)
-- -----------------------------------------------------------
CREATE TABLE Restock_Item (
    restock_item_id       INT UNSIGNED   AUTO_INCREMENT PRIMARY KEY,
    restock_id            INT UNSIGNED   NOT NULL,
    product_id            INT UNSIGNED   NOT NULL,
    quantity_added        INT            NOT NULL CHECK (quantity_added > 0),
    cost_price_at_restock DECIMAL(10,2)  NOT NULL DEFAULT 0.00 CHECK (cost_price_at_restock >= 0),
    expiration_date       DATE           NULL,

    CONSTRAINT fk_ri_restock FOREIGN KEY (restock_id)
        REFERENCES Restock_Transaction(restock_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_ri_product FOREIGN KEY (product_id)
        REFERENCES Product(product_id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

-- -----------------------------------------------------------
--  7. Customer  (FK → Sale, per ERD — Sale has customer_id)
-- -----------------------------------------------------------
CREATE TABLE Customer (
    customer_id       INT UNSIGNED   AUTO_INCREMENT PRIMARY KEY,
    customer_name     VARCHAR(100)   NOT NULL,
    contact_number    VARCHAR(20)    NOT NULL,
    address           TEXT           NOT NULL,
    total_outstanding DECIMAL(12,2)  NOT NULL DEFAULT 0.00 CHECK (total_outstanding >= 0),
    created_at        DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- -----------------------------------------------------------
--  8. Sale  (FK → Customer)
-- -----------------------------------------------------------
CREATE TABLE Sale (
    sale_id          INT UNSIGNED   AUTO_INCREMENT PRIMARY KEY,
    customer_id      INT UNSIGNED   NULL,
    payment_method   ENUM('cash','credit') NOT NULL,
    total_amount     DECIMAL(12,2)  NOT NULL DEFAULT 0.00 CHECK (total_amount >= 0),
    amount_tendered  DECIMAL(12,2)  NULL     CHECK (amount_tendered >= 0),
    change_given     DECIMAL(12,2)  NULL     CHECK (change_given >= 0),
    total_cost       DECIMAL(12,2)  NOT NULL DEFAULT 0.00 CHECK (total_cost >= 0),
    profit           DECIMAL(12,2)  GENERATED ALWAYS AS (total_amount - total_cost) STORED,
    sale_date        DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sale_customer FOREIGN KEY (customer_id)
        REFERENCES Customer(customer_id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB;

-- -----------------------------------------------------------
--  9. Sale_Item  (FK → Sale, Product)
-- -----------------------------------------------------------
CREATE TABLE Sale_Item (
    sale_item_id       INT UNSIGNED   AUTO_INCREMENT PRIMARY KEY,
    sale_id            INT UNSIGNED   NOT NULL,
    product_id         INT UNSIGNED   NOT NULL,
    quantity_sold      INT            NOT NULL CHECK (quantity_sold > 0),
    unit_price_at_sale DECIMAL(10,2)  NOT NULL DEFAULT 0.00 CHECK (unit_price_at_sale >= 0),
    unit_cost_at_sale  DECIMAL(10,2)  NOT NULL DEFAULT 0.00 CHECK (unit_cost_at_sale >= 0),
    subtotal           DECIMAL(12,2)  GENERATED ALWAYS AS (unit_price_at_sale * quantity_sold) STORED,

    CONSTRAINT fk_si_sale    FOREIGN KEY (sale_id)
        REFERENCES Sale(sale_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_si_product FOREIGN KEY (product_id)
        REFERENCES Product(product_id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

-- -----------------------------------------------------------
--  10. Debt  (FK → Sale, UNIQUE on sale_id)
-- -----------------------------------------------------------
CREATE TABLE Debt (
    debt_id           INT UNSIGNED   AUTO_INCREMENT PRIMARY KEY,
    sale_id           INT UNSIGNED   NOT NULL UNIQUE,
    original_amount   DECIMAL(12,2)  NOT NULL CHECK (original_amount > 0),
    remaining_balance DECIMAL(12,2)  NOT NULL CHECK (remaining_balance >= 0),
    settlement_date   DATE           NULL,
    status            ENUM('Unpaid','Partially Paid','Fully Paid') NOT NULL DEFAULT 'Unpaid',
    created_at        DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_debt_sale FOREIGN KEY (sale_id)
        REFERENCES Sale(sale_id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

-- -----------------------------------------------------------
--  11. Debt_Payment  (FK → Debt)
-- -----------------------------------------------------------
CREATE TABLE Debt_Payment (
    payment_id   INT UNSIGNED   AUTO_INCREMENT PRIMARY KEY,
    debt_id      INT UNSIGNED   NOT NULL,
    payment_date DATE           NOT NULL DEFAULT (CURRENT_DATE),
    amount_paid  DECIMAL(12,2)  NOT NULL CHECK (amount_paid > 0),

    CONSTRAINT fk_dp_debt FOREIGN KEY (debt_id)
        REFERENCES Debt(debt_id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;


-- ============================================================
--  INDEXES  (Requirement: index a frequently searched column)
-- ============================================================

-- SKU: most common single-product lookup
CREATE INDEX idx_product_sku         ON Product(sku);
-- Filter products by category
CREATE INDEX idx_product_category    ON Product(category_id);
-- Stock status alerts page
CREATE INDEX idx_product_status      ON Product(status);
-- All products belonging to a user
CREATE INDEX idx_product_user        ON Product(user_id);
-- Inventory log: always filtered by product then sorted by date
CREATE INDEX idx_invlog_product_date ON Inventory_Log(product_id, log_date);
-- Sales joined by customer or filtered by date
CREATE INDEX idx_sale_customer       ON Sale(customer_id);
CREATE INDEX idx_sale_date           ON Sale(sale_date);
-- Debt payments grouped by debt
CREATE INDEX idx_debtpayment_debt    ON Debt_Payment(debt_id);


-- ============================================================
--  TRIGGERS
-- ============================================================

DELIMITER $$

-- -----------------------------------------------------------
--  TRIGGER 1 — Auto-generate SKU after Product INSERT
--  Format: <FIRST-3-LETTERS uppercase><product_id zero-padded to 6>
--  e.g. "Coca-Cola" → COC000001
-- -----------------------------------------------------------
CREATE TRIGGER trg_product_sku_generate
AFTER INSERT ON Product
FOR EACH ROW
BEGIN
    DECLARE v_prefix VARCHAR(3);
    SET v_prefix = UPPER(LEFT(REPLACE(REPLACE(NEW.product_name, ' ', ''), '-', ''), 3));
    UPDATE Product
    SET sku = CONCAT(v_prefix, LPAD(NEW.product_id, 6, '0'))
    WHERE product_id = NEW.product_id;
END$$

DELIMITER $$

CREATE TRIGGER trg_product_status_update
BEFORE UPDATE ON Product
FOR EACH ROW
BEGIN
    IF NEW.quantity = 0 THEN
        SET NEW.status = 'Out of Stock';
    ELSEIF NEW.quantity BETWEEN 1 AND 15 THEN
        SET NEW.status = 'Low Stock';
    ELSE
        SET NEW.status = 'In Stock';
    END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------------
--  TRIGGER 3 — Deduct stock + log when a Sale_Item is inserted
-- -----------------------------------------------------------
CREATE TRIGGER trg_sale_item_deduct_stock
AFTER INSERT ON Sale_Item
FOR EACH ROW
BEGIN
    DECLARE v_stock_before INT;

    SELECT quantity INTO v_stock_before
    FROM Product
    WHERE product_id = NEW.product_id;

    UPDATE Product
    SET quantity = quantity - NEW.quantity_sold
    WHERE product_id = NEW.product_id;

    INSERT INTO Inventory_Log
        (product_id, movement_type, quantity_change,
         stock_before, stock_after, reference_type, reference_id)
    VALUES
        (NEW.product_id, 'out', NEW.quantity_sold,
         v_stock_before, v_stock_before - NEW.quantity_sold,
         'sale', NEW.sale_id);
END$$

-- -----------------------------------------------------------
--  TRIGGER 4 — Add stock + log when a Restock_Item is inserted
-- -----------------------------------------------------------
CREATE TRIGGER trg_restock_item_add_stock
AFTER INSERT ON Restock_Item
FOR EACH ROW
BEGIN
    DECLARE v_stock_before INT;

    SELECT quantity INTO v_stock_before
    FROM Product
    WHERE product_id = NEW.product_id;

    UPDATE Product
    SET quantity = quantity + NEW.quantity_added
    WHERE product_id = NEW.product_id;

    INSERT INTO Inventory_Log
        (product_id, movement_type, quantity_change,
         stock_before, stock_after, reference_type, reference_id)
    VALUES
        (NEW.product_id, 'in', NEW.quantity_added,
         v_stock_before, v_stock_before + NEW.quantity_added,
         'restock', NEW.restock_item_id);
END$$

-- -----------------------------------------------------------
--  TRIGGER 5 — Update Debt balance + status after each payment
-- -----------------------------------------------------------
CREATE TRIGGER trg_debt_payment_after_insert
AFTER INSERT ON Debt_Payment
FOR EACH ROW
BEGIN
    DECLARE v_remaining DECIMAL(12,2);
    DECLARE v_customer_id INT UNSIGNED;

    -- Deduct the payment from remaining balance
    UPDATE Debt
    SET remaining_balance = remaining_balance - NEW.amount_paid
    WHERE debt_id = NEW.debt_id;

    -- Re-read the updated balance
    SELECT remaining_balance INTO v_remaining
    FROM Debt
    WHERE debt_id = NEW.debt_id;

    IF v_remaining <= 0 THEN
        -- Fully paid
        UPDATE Debt
        SET status            = 'Fully Paid',
            remaining_balance = 0,
            settlement_date   = NEW.payment_date
        WHERE debt_id = NEW.debt_id;

        -- Get the customer_id from the linked sale
        SELECT s.customer_id INTO v_customer_id
        FROM Debt d
        JOIN Sale s ON s.sale_id = d.sale_id
        WHERE d.debt_id = NEW.debt_id;

        -- Reduce customer total_outstanding
        IF v_customer_id IS NOT NULL THEN
            UPDATE Customer
            SET total_outstanding = GREATEST(total_outstanding - NEW.amount_paid, 0)
            WHERE customer_id = v_customer_id;
        END IF;
    ELSE
        -- Partially paid
        UPDATE Debt
        SET status = 'Partially Paid'
        WHERE debt_id = NEW.debt_id AND status = 'Unpaid';
    END IF;
END$$

DELIMITER ;


-- ============================================================
--  STORED PROCEDURES
-- ============================================================

DELIMITER $$

-- -----------------------------------------------------------
--  SP 1 — Process a Cash Sale
--  Creates Sale + Sale_Item in one transaction.
--  Trigger trg_sale_item_deduct_stock handles stock deduction.
-- -----------------------------------------------------------
CREATE PROCEDURE sp_process_cash_sale(
    IN  p_user_id     INT UNSIGNED,
    IN  p_product_ids TEXT,
    IN  p_quantities  TEXT,
    IN  p_tendered    DECIMAL(12,2),
    OUT p_sale_id     INT UNSIGNED,
    OUT p_message     VARCHAR(255)
)
proc: BEGIN
    DECLARE v_count      INT DEFAULT 1;
    DECLARE v_index      INT DEFAULT 1;
    DECLARE v_product_id INT UNSIGNED;
    DECLARE v_qty        INT;
    DECLARE v_retail     DECIMAL(10,2);
    DECLARE v_cost       DECIMAL(10,2);
    DECLARE v_stock      INT;
    DECLARE v_total      DECIMAL(12,2) DEFAULT 0.00;
    DECLARE v_tot_cost   DECIMAL(12,2) DEFAULT 0.00;
    DECLARE v_sale_id    INT UNSIGNED;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET p_sale_id = 0;
        SET p_message = 'Sale failed: a database error occurred.';
    END;

    SET v_count = 1 + LENGTH(p_product_ids) - LENGTH(REPLACE(p_product_ids, ',', ''));

    START TRANSACTION;

        -- Insert sale header with placeholder total
        INSERT INTO Sale (customer_id, payment_method, total_amount, amount_tendered, change_given, total_cost, sale_date)
        VALUES (NULL, 'cash', 0.00, p_tendered, 0.00, 0.00, NOW());

        SET v_sale_id = LAST_INSERT_ID();

        WHILE v_index <= v_count DO
            SET v_product_id = CAST(TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(p_product_ids, ',', v_index), ',', -1)) AS UNSIGNED);
            SET v_qty        = CAST(TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(p_quantities,  ',', v_index), ',', -1)) AS UNSIGNED);

            SELECT retail_price, cost_price, quantity
            INTO   v_retail, v_cost, v_stock
            FROM   Product
            WHERE  product_id = v_product_id AND user_id = p_user_id
            FOR UPDATE;

            IF v_retail IS NULL THEN
                ROLLBACK;
                SET p_sale_id = 0;
                SET p_message = CONCAT('Product ID ', v_product_id, ' not found.');
                LEAVE proc;
            END IF;

            IF v_stock < v_qty THEN
                ROLLBACK;
                SET p_sale_id = 0;
                SET p_message = CONCAT('Insufficient stock for product ID ', v_product_id);
                LEAVE proc;
            END IF;

            INSERT INTO Sale_Item (sale_id, product_id, quantity_sold, unit_price_at_sale, unit_cost_at_sale)
            VALUES (v_sale_id, v_product_id, v_qty, v_retail, v_cost);

            SET v_total    = v_total    + (v_retail * v_qty);
            SET v_tot_cost = v_tot_cost + (v_cost   * v_qty);
            SET v_index    = v_index + 1;
        END WHILE;

        -- Update sale header with real totals
        UPDATE Sale
        SET total_amount    = v_total,
            amount_tendered = p_tendered,
            change_given    = p_tendered - v_total,
            total_cost      = v_tot_cost
        WHERE sale_id = v_sale_id;

    COMMIT;

    SET p_sale_id = v_sale_id;
    SET p_message = 'Sale created successfully.';
END proc$$

-- -----------------------------------------------------------
--  SP 2 — Process a Credit Sale
--  Creates Customer + Sale + Sale_Item + Debt in one transaction.
-- -----------------------------------------------------------
CREATE PROCEDURE sp_process_credit_sale(
    IN  p_user_id        INT UNSIGNED,
    IN  p_customer_name  VARCHAR(100),
    IN  p_contact_number VARCHAR(20),
    IN  p_address        TEXT,
    IN  p_product_ids    TEXT,
    IN  p_quantities     TEXT,
    OUT p_sale_id        INT UNSIGNED,
    OUT p_customer_id    INT UNSIGNED,
    OUT p_debt_id        INT UNSIGNED,
    OUT p_message        VARCHAR(255)
)
proc: BEGIN
    DECLARE v_count      INT DEFAULT 1;
    DECLARE v_index      INT DEFAULT 1;
    DECLARE v_product_id INT UNSIGNED;
    DECLARE v_qty        INT;
    DECLARE v_retail     DECIMAL(10,2);
    DECLARE v_cost       DECIMAL(10,2);
    DECLARE v_stock      INT;
    DECLARE v_total      DECIMAL(12,2) DEFAULT 0.00;
    DECLARE v_tot_cost   DECIMAL(12,2) DEFAULT 0.00;
    DECLARE v_sale_id    INT UNSIGNED;
    DECLARE v_cust_id    INT UNSIGNED;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET p_sale_id     = 0;
        SET p_customer_id = 0;
        SET p_debt_id     = 0;
        SET p_message     = 'Credit sale failed: a database error occurred.';
    END;

    SET v_count = 1 + LENGTH(p_product_ids) - LENGTH(REPLACE(p_product_ids, ',', ''));

    START TRANSACTION;

        -- Create the customer record
        INSERT INTO Customer (customer_name, contact_number, address, total_outstanding)
        VALUES (p_customer_name, p_contact_number, p_address, 0.00);

        SET v_cust_id = LAST_INSERT_ID();

        -- Insert sale header placeholder
        INSERT INTO Sale (customer_id, payment_method, total_amount, amount_tendered, change_given, total_cost, sale_date)
        VALUES (v_cust_id, 'credit', 0.00, NULL, NULL, 0.00, NOW());

        SET v_sale_id = LAST_INSERT_ID();

        WHILE v_index <= v_count DO
            SET v_product_id = CAST(TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(p_product_ids, ',', v_index), ',', -1)) AS UNSIGNED);
            SET v_qty        = CAST(TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(p_quantities,  ',', v_index), ',', -1)) AS UNSIGNED);

            SELECT retail_price, cost_price, quantity
            INTO   v_retail, v_cost, v_stock
            FROM   Product
            WHERE  product_id = v_product_id AND user_id = p_user_id
            FOR UPDATE;

            IF v_retail IS NULL THEN
                ROLLBACK;
                SET p_sale_id = 0; SET p_customer_id = 0; SET p_debt_id = 0;
                SET p_message = CONCAT('Product ID ', v_product_id, ' not found.');
                LEAVE proc;
            END IF;

            IF v_stock < v_qty THEN
                ROLLBACK;
                SET p_sale_id = 0; SET p_customer_id = 0; SET p_debt_id = 0;
                SET p_message = CONCAT('Insufficient stock for product ID ', v_product_id);
                LEAVE proc;
            END IF;

            INSERT INTO Sale_Item (sale_id, product_id, quantity_sold, unit_price_at_sale, unit_cost_at_sale)
            VALUES (v_sale_id, v_product_id, v_qty, v_retail, v_cost);

            SET v_total    = v_total    + (v_retail * v_qty);
            SET v_tot_cost = v_tot_cost + (v_cost   * v_qty);
            SET v_index    = v_index + 1;
        END WHILE;

        -- Update sale totals
        UPDATE Sale
        SET total_amount = v_total, total_cost = v_tot_cost
        WHERE sale_id = v_sale_id;

        -- Update customer outstanding balance
        UPDATE Customer
        SET total_outstanding = v_total
        WHERE customer_id = v_cust_id;

        -- Create debt record
        INSERT INTO Debt (sale_id, original_amount, remaining_balance, status)
        VALUES (v_sale_id, v_total, v_total, 'Unpaid');

        SET p_debt_id = LAST_INSERT_ID();

    COMMIT;

    SET p_sale_id     = v_sale_id;
    SET p_customer_id = v_cust_id;
    SET p_message     = 'Credit sale created successfully.';
END proc$$

-- -----------------------------------------------------------
--  SP 3 — Manual Inventory Adjustment
-- -----------------------------------------------------------
DELIMITER $$

CREATE PROCEDURE sp_manual_inventory_adjustment(
    IN  p_product_id      INT UNSIGNED,
    IN  p_quantity_change INT,
    IN  p_movement_type   ENUM('in','out'),
    IN  p_reason          ENUM(
                              'Damaged Goods',
                              'Expired Items',
                              'Stock Count Correction',
                              'Theft/Loss',
                              'Returned to Supplier',
                              'Other'
                          ),
    OUT p_message         VARCHAR(255)
)
proc: BEGIN

    DECLARE v_stock_before INT DEFAULT NULL;
    DECLARE v_stock_after  INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET p_message = 'Adjustment failed: a database error occurred.';
    END;

    START TRANSACTION;

        SELECT quantity
        INTO v_stock_before
        FROM Product
        WHERE product_id = p_product_id
        FOR UPDATE;

        IF v_stock_before IS NULL THEN
            ROLLBACK;
            SET p_message = 'Product not found.';
            LEAVE proc;
        END IF;

        IF p_movement_type = 'in' THEN

            SET v_stock_after = v_stock_before + p_quantity_change;

        ELSE

            IF v_stock_before < p_quantity_change THEN
                ROLLBACK;
                SET p_message = 'Cannot subtract more than current stock.';
                LEAVE proc;
            END IF;

            SET v_stock_after = v_stock_before - p_quantity_change;

        END IF;

        UPDATE Product
        SET quantity = v_stock_after
        WHERE product_id = p_product_id;

        INSERT INTO Inventory_Log (
            product_id,
            movement_type,
            quantity_change,
            stock_before,
            stock_after,
            reference_type,
            reference_id,
            adjustment_reason
        )
        VALUES (
            p_product_id,
            p_movement_type,
            p_quantity_change,
            v_stock_before,
            v_stock_after,
            'manual',
            NULL,
            p_reason
        );

    COMMIT;

    SET p_message = 'Adjustment applied successfully.';

END proc$$

DELIMITER ;

-- -----------------------------------------------------------
--  SP 4 — Record a Debt Payment
-- -----------------------------------------------------------
DELIMITER $$

CREATE PROCEDURE sp_record_debt_payment(
    IN  p_debt_id      INT UNSIGNED,
    IN  p_amount_paid  DECIMAL(12,2),
    IN  p_payment_date DATE,
    OUT p_message      VARCHAR(255)
)
proc: BEGIN

    DECLARE v_remaining DECIMAL(12,2) DEFAULT NULL;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET p_message = 'Payment failed: a database error occurred.';
    END;

    START TRANSACTION;

        SELECT remaining_balance
        INTO v_remaining
        FROM Debt
        WHERE debt_id = p_debt_id
        FOR UPDATE;

        IF v_remaining IS NULL THEN
            ROLLBACK;
            SET p_message = 'Debt record not found.';
            LEAVE proc;
        END IF;

        IF p_amount_paid <= 0 THEN
            ROLLBACK;
            SET p_message = 'Payment amount must be greater than zero.';
            LEAVE proc;
        END IF;

        IF p_amount_paid > v_remaining THEN
            ROLLBACK;
            SET p_message = 'Payment exceeds remaining balance.';
            LEAVE proc;
        END IF;

        INSERT INTO Debt_Payment (
            debt_id,
            payment_date,
            amount_paid
        )
        VALUES (
            p_debt_id,
            p_payment_date,
            p_amount_paid
        );

    COMMIT;

    SET p_message = 'Payment recorded successfully.';

END proc$$

DELIMITER ;     



-- ============================================================
--  VIEWS
-- ============================================================

-- -----------------------------------------------------------
--  VIEW 1 — Manager Dashboard
--  Joins: Product, Category, User, Sale_Item, Sale
--  Uses: COUNT(), SUM(), LEFT JOIN
-- -----------------------------------------------------------
CREATE OR REPLACE VIEW vw_manager_dashboard AS
SELECT
    p.product_id,
    p.product_name,
    p.sku,
    p.user_id,
    u.store_name,
    c.category_name,
    p.quantity                                                AS current_stock,
    p.status                                                  AS stock_status,
    p.retail_price,
    p.cost_price,
    p.expiration_date,
    COALESCE(SUM(si.quantity_sold), 0)                        AS total_units_sold,
    COALESCE(SUM(si.subtotal), 0)                             AS total_revenue,
    COALESCE(SUM(si.quantity_sold * si.unit_cost_at_sale), 0) AS total_cogs,
    COALESCE(SUM(si.subtotal - si.quantity_sold * si.unit_cost_at_sale), 0) AS gross_profit,
    COUNT(DISTINCT si.sale_id)                                AS number_of_transactions
FROM Product p
JOIN Category   c  ON c.category_id = p.category_id
JOIN User       u  ON u.user_id     = p.user_id
LEFT JOIN Sale_Item si ON si.product_id = p.product_id
LEFT JOIN Sale       s  ON s.sale_id    = si.sale_id
GROUP BY
    p.product_id, p.product_name, p.sku, p.user_id, u.store_name,
    c.category_name, p.quantity, p.status, p.retail_price,
    p.cost_price, p.expiration_date;

-- -----------------------------------------------------------
--  VIEW 2 — Customer Credit / Outstanding Balances
--  Joins: Customer, Sale, Debt, Debt_Payment
-- -----------------------------------------------------------
CREATE OR REPLACE VIEW vw_customer_outstanding AS
SELECT
    cu.customer_id,
    cu.customer_name,
    cu.contact_number,
    cu.address,
    cu.total_outstanding,
    COUNT(DISTINCT d.debt_id)               AS total_credit_transactions,
    COALESCE(SUM(d.original_amount), 0)     AS total_borrowed,
    COALESCE(SUM(d.remaining_balance), 0)   AS total_remaining,
    COALESCE(SUM(d.original_amount) - SUM(d.remaining_balance), 0) AS total_paid,
    MAX(dp.payment_date)                    AS last_payment_date
FROM Customer cu
LEFT JOIN Sale          s  ON s.customer_id = cu.customer_id
LEFT JOIN Debt          d  ON d.sale_id     = s.sale_id
LEFT JOIN Debt_Payment dp  ON dp.debt_id   = d.debt_id
GROUP BY cu.customer_id, cu.customer_name, cu.contact_number,
         cu.address, cu.total_outstanding;

-- -----------------------------------------------------------
--  VIEW 3 — Low-Stock & Out-of-Stock Alerts
--  Joins: Product, Category
-- -----------------------------------------------------------
CREATE OR REPLACE VIEW vw_stock_alerts AS
SELECT
    p.product_id,
    p.sku,
    p.product_name,
    c.category_name,
    p.quantity,
    p.low_stock_threshold,
    p.status,
    p.expiration_date,
    p.user_id
FROM Product p
JOIN Category c ON c.category_id = p.category_id
WHERE p.status IN ('Low Stock','Out of Stock')
ORDER BY p.quantity ASC;

-- -----------------------------------------------------------
--  VIEW 4 — Daily Sales Summary
--  Uses: COUNT(), SUM(), GROUP BY
-- -----------------------------------------------------------
CREATE OR REPLACE VIEW vw_daily_sales_summary AS
SELECT
    DATE(s.sale_date)                                            AS sale_day,
    COUNT(DISTINCT s.sale_id)                                    AS total_transactions,
    SUM(s.total_amount)                                          AS total_revenue,
    SUM(s.total_cost)                                            AS total_cost,
    SUM(s.profit)                                                AS total_profit,
    SUM(CASE WHEN s.payment_method = 'cash'   THEN 1 ELSE 0 END) AS cash_sales,
    SUM(CASE WHEN s.payment_method = 'credit' THEN 1 ELSE 0 END) AS credit_sales
FROM Sale s
GROUP BY DATE(s.sale_date)
ORDER BY sale_day DESC;

-- -----------------------------------------------------------
--  VIEW 5 — Inventory Movement History (audit log)
--  Joins: Inventory_Log, Product, Category
-- -----------------------------------------------------------
CREATE OR REPLACE VIEW vw_inventory_movements AS
SELECT
    il.log_id,
    il.log_date,
    p.product_id,
    p.user_id,
    p.sku,
    p.product_name,
    c.category_name,
    il.movement_type,
    il.quantity_change,
    il.stock_before,
    il.stock_after,
    il.reference_type,
    il.reference_id,
    il.adjustment_reason
FROM Inventory_Log il
JOIN Product  p ON p.product_id  = il.product_id
JOIN Category c ON c.category_id = p.category_id
ORDER BY il.log_date DESC;

-- ============================================================
--  END OF SCHEMA
-- ============================================================